### ISSUE TITLE
Logfiles everywhere

### ISSUE THREAD

**Issue by hanneskiene** [juli9797/ssf#5]
Logfiles are stored where ssf is called;
need to either only log when log arg is provided or fix log location

**Comment by hanneskiene** [comment]
@juli9797 ?

**Comment by juli9797** [comment]
oh shit, i suggest we store them in ~/.config/ssf/log.txt 
Might be the wrong place but this will work!
@hanneskiene

**Comment by juli9797** [comment]
I changed my mind: logfiles are BLOAT we don't need them (gdb: *EXISTS*). @hanneskiene
